baseURL = 'https://cornwallwargamesassociation.org/'
languageCode = 'en-us'
title = 'Cornwall Wargames Association'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true
allowRemoteResources = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  [module.imports]
    disable = false
    ignoreConfig = false
    ignoreImports = false
    path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[languages]
  [languages.en]
    title = "Cornwall Wargames Association"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "images/favicon.webp"
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

  [params.ananke.social.follow]
    networks = [
      "facebook"
    ]

  [params.ananke.social.facebook]
    username = "384835921661980"
